### ISSUE TITLE
Add Geometry Validation functions from PostGIS

### ISSUE THREAD

**Issue by blikij** [sheinbergon/dremio-udf-gis#39]
Would it be possible to add the geometry validation functions. Such as ST_IsValid, ST_IsValidDetail, ST_IsValidReason and ST_MakeValid? The European Environment Agency could use this excellent work in our data reporting tool making spatial validation  as well possible.

**Comment by sheinbergon** [comment]
Hi @blikij 

I can add this PostGIS like functionality, sure.
I'll make it a part of the upcoming release.

Bear in mind that much like PostGIS, validation will work on sane geometries only (for example, you can't create a polygon comprised of a non closed ring). Such shapes will cause queries to fail (which is also what happens in PostGIS)

It will of course, work for softer errors (like self Intersecrting polygons)

**Comment by sheinbergon** [comment]
@bliki Bothj `ST_IsValid` and `ST_IsValidReason` (including their ESRI flag variants) will be part of the next release (27.2)
`ST_IsValidDetail` would not be implemented for now, as I've yet to unrevel the whole expand object thingy in Dremio ( there now composite tuple types like Postgres). I'll also try and push `ST_MakeValid` into that relese, but it'll require more work

**Comment by blikij** [comment]
Thank you so much. ST_IsValidDetail is not that crucial for us. If the other cn be implemented we have something I can use in production.

**Comment by sheinbergon** [comment]
Do you plan on using `ST_MakeValid` in production?

**Comment by blikij** [comment]
> Do you plan on using `ST_MakeValid` in production?

Yes, It would allow us to perform additional validations on the data. If the errors are minor... The result would not be written back, instead we would write into an additional table... (using a create table... select...)

**Comment by sheinbergon** [comment]
OK. Got it. I'll make an effort to add that to the release plan

**Comment by sheinbergon** [comment]
@blikij I can confirm that an implementation of `ST_MakeValid`, based on JTS's `GeometryFixer` will make it into the upcoming release. bear in mind this is somewhat experimental, as results seem to differ from the standard OGC implementation, and can occasionaly provide unexpected results

**Comment by sheinbergon** [comment]
Released in `https://github.com/sheinbergon/dremio-udf-gis/releases/tag/0.8.6`

**Comment by sheinbergon** [comment]
Released in [0.8.6](https://github.com/sheinbergon/dremio-udf-gis/releases/tag/0.8.6)
