### ISSUE TITLE
UnsupportedClassVersionError: STGeomFromText has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by jaysnm** [sheinbergon/dremio-udf-gis#4]
Hello @sheinbergon 

Thank you for the effort and this amazing tool. 
I was trying it and bumped into this error!

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/20385376/163990194-5d1a856b-5cdd-4506-bdf2-de62f551e55b.png">

I'm using Dremio 20.1, fresh installation in a VM.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/20385376/163990332-5c3f063a-c00a-47d3-a858-9cd59fae2a18.png">

Would also be great to see more usage examples. 
Thanks a lot and good work!

**Comment by sheinbergon** [comment]
Hi.

Thank you for the warm words (_starring == caring_)
For your issue - Dremio 20.x now supports JDK 11, and this code is compiled for JDK11.
I'd strongly recommend migrating your installation to JDK 11, which can now use more advanced GC as part of the mainline build (Shenandoah/ZGC)  (starting from 11.0.9). 

I'll perhaps add JDK8 build target in an upcoming release.

As for more usage samples - for now, you can follow [Drill](https://drill.apache.org/docs/gis-functions/) for usage direcative.
But you are correct, I'll add more sample to this GH project soon.

**Comment by jaysnm** [comment]
Thanks for reverting Idan. I don't know how starring slipped out of my mind after creating the issue, I was up to starring and I have already.

You answered my query in full, Thanks!

**Comment by bigfacewo** [comment]
@jaysnm It seems that dremio OSS cannot be compiled in JDK 11. Is there any relevant document to share?
thank you

**Comment by sheinbergon** [comment]
@bigfacewo please  open a separate issue describing your errors in detail, 10x

**Comment by jaysnm** [comment]
Hello @bigfacewo 

I did not compile dremio from source but rather used already compiled archives from [dremio download server](https://download.dremio.com/community-server/). Perhaps you may want to create a new issue for this!

**Comment by bigfacewo** [comment]
@jaysnm "Dremio community" 20.1 should be compiled in "JDK1.8" or "jdk1.9". This is the definition of JDK version in Maven:https://github.com/dremio/dremio-oss/blob/31bc9b7ce0aa88ac2ab8ebcbc9fb69fb0d2744a8/pom.xml#L524

I tried to modify the definition and compile using jdk11, but it didn't succeed, so I want to know, even if dremio uses jdk1.8 compilation, can it also run in JDK 11? I don't know this very well.

**Comment by bigfacewo** [comment]
@jaysnm Thank you for telling me that.
